[profile.ci.fuzz]
runs = 10_000

[profile.default]
src = 'contracts'
out = 'artifacts'

fs_permissions = [{ access = "read", path = "./"}]

[rpc_endpoints]
arbitrum = "${ARBITRUM_RPC_URL}"

[etherscan]
arbitrum = {key = "${ARBISCAN_API_KEY}", url = "https://api.arbiscan.io" }